In [41]:
import numpy as np
a= np.random.randn(20,4)
b= np.random.randn(1,1)
c=a*b

In [42]:
a

array([[ 0.1259032 ,  1.16742082,  0.16794242,  1.97148114],
       [-0.83758674, -0.45942197,  1.55952272, -2.50808641],
       [-0.60978111,  0.72916497, -0.19017897,  0.27764158],
       [-1.05608897,  0.58269186,  0.57034358,  0.11681301],
       [ 0.08121309, -0.8376465 , -0.77094887,  2.45543351],
       [ 0.3133705 , -0.98773598,  1.12525164, -0.41652811],
       [-1.38981962,  1.1037284 , -1.21035791, -0.85092303],
       [ 1.22078634, -0.65864994, -1.91695417,  0.55370177],
       [ 0.58764132, -0.78135214,  0.8243664 ,  0.0136263 ],
       [ 0.04160789,  0.53068615, -0.49769342,  0.32363919],
       [ 0.21829333, -0.616444  , -0.34991043, -0.65918829],
       [ 1.881667  , -1.30757994,  0.22602111, -0.61235124],
       [-0.14998195,  0.52361547,  0.1171707 , -0.56281565],
       [ 0.49011947,  0.46831162, -0.2812779 ,  0.50414534],
       [-0.99549585, -0.25786735,  0.33792481,  0.93338329],
       [ 0.4413227 ,  1.79616534, -0.83643036,  0.67369089],
       [-0.30954518, -0.

In [43]:
import numpy as np
a= np.random.randn(3,4,1)
b= np.random.randn(3,1,2)
c=np.random.randn(3,1,1)
d=c + a*b
d.shape


(3, 4, 2)

In [46]:
a

array([[[-0.94840594],
        [-0.86568978],
        [ 0.86939807],
        [-0.52487017]],

       [[-0.57021025],
        [-0.80438897],
        [-0.10857651],
        [ 0.89312593]],

       [[ 0.64510048],
        [-0.25909825],
        [ 1.51549539],
        [-1.11118844]]])

In [49]:
b

array([[[-1.71418118,  0.46032577]],

       [[ 1.64956738, -0.70091163]],

       [[ 1.13443592,  1.69658478]]])

In [4]:
x=5
y=6
x *= y + 2
x

40

In [5]:
x = 3893 // 10
x

389

In [10]:
A = '___'.join([' ', ' '])

print('\n'.join((A,B,A,B,A,B,A,B,A)))

 ___ 
AAA
 ___ 
AAA
 ___ 
AAA
 ___ 
AAA
 ___ 


In [21]:
# Here’s the starter code:
def remove_duplicates(x):
    ### START CODE HERE ###
    new_list =[]
    for i in range(0,len(x)):
        for j in range(0,len(new_list)):
            if x[i] != new_list[j]:
                new_list[i] = x[i]
                break

    ### END CODE HERE ###
    return new_list



In [22]:
remove_duplicates([1,3,5,6,2,3,4])

[]

In [23]:
from collections import OrderedDict
list(OrderedDict.fromkeys([1,3,5,6,2,3,4]))

[1, 3, 5, 6, 2, 4]

In [24]:
# Here’s the starter code:
from collections import OrderedDict
def remove_duplicates(x):  
    ### START CODE HERE ###
    new_list = list(OrderedDict.fromkeys(x))
        
        


    ### END CODE HERE ###
    return new_list



In [26]:
remove_duplicates([1,3,5,6,2,3,4,1,1,1])

[1, 3, 5, 6, 2, 4]

In [33]:
def find_num(sorted_list, num):
    ### START CODE HERE ###
    for i in range(0, len(sorted_list)):
        print(i)
        print(sorted_list[i])
        if sorted_list[i] == num:
            print(num)
            return True
        
        else:
            return False

In [34]:
find_num([1,2,3,4],3)

0
1


False

In [40]:
def find_num(sorted_list, num):
    ### START CODE HERE ###
    counter = 0 
    for i in range(0, len(sorted_list)):
        print(sorted_list[i])

        if sorted_list[i] == num:
            counter = 1
    if counter == 1:
        return True
    else:
        return False
        
find_num([1,2,3,4],1)        

1
2
3
4


True