In [25]:
import numpy as np
x = np.arange(6)

In [26]:
x

array([0, 1, 2, 3, 4, 5])

In [28]:
np.where(x>1)

(array([2, 3, 4, 5]),)

In [29]:
x = np.arange(9.).reshape(3, 3)
x

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [32]:
np.where( x > 5 )

(array([2, 2, 2]), array([0, 1, 2]))

In [8]:
import numpy as np
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=np.float32)
print(X)
X.shape

1.0


(4, 2)